# Generated by Django 5.0.1 on 2024-12-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at'], 'verbose_name': '문의', 'verbose_name_plural': '문의 목록'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='job',
            field=models.CharField(choices=[('influencer', '인플루언서'), ('business', '1인 사업'), ('instructor', '1인 강사'), ('freelancer', '프리랜서'), ('artist', '예체능'), ('other', '기타')], max_length=20, verbose_name='직업'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='문의사항'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='연락처'),
        ),
    ]
