name : deploy homepage

on: # 아래 job을 실행시킬 상황
  push:
    branches: [ main ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest # 실행될 인스턴스 OS와 버전

    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@master # ssh 접속하는 오픈소스
        with:
          host: ${{ secrets.EC2_IP }} # 인스턴스 IP
          username: ${{ secrets.EC2_USER }} # 우분투 아이디
          key: ${{ secrets.EC2_PRIVATE_KEY }} # ec2 instance pem key
          port: ${{ secrets.EC2_SSH_PORT }} # 접속포트
          script: | # 실행할 스크립트
            cd /home/ubuntu/homepage/backend
            git pull origin main
            sudo docker stop django
            sudo docker rm django
            sudo docker rmi backend
            sudo docker build -t backend .
            sudo docker run -p 8000:8000 -d --name django --env-file .env backend